### ISSUE TITLE
Plotly browser plot requires internet connection

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#447] opened 2022-01-07 12:54 UTC
this is not so cool :)

**Comment by Alexboiboi** [comment] 2022-01-07 22:22
I cannot reproduce this. For me it works without internet connection

**Comment by OrtnerMichael** [comment] 2022-01-10 18:46
I will try to reproduce my plotly problem - in short: sometimes the browser seems blocked and displays nothing - stays on the loading screen.

**Comment by Alexboiboi** [comment] 2022-01-25 16:53
can we close this?

**Closed** 2022-01-26 13:01 UTC
