### ISSUE TITLE
[BUG] - The MAX magnitude of field will change when a circular rotate with a angle in a 3D space, however, we set a sensor in a randon point, and when the circular rotate and the sensor will rotate same angle, the magnetic value in the sensor will keep same. 

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#371] opened 2021-07-24 11:39 UTC
for i in range (60):   
         coil = magpy.current.Circular(current, diameter=2, position=(0, 0, 0))
        rotation_angle = 5 * i
        coil.rotate_from_angax(angle=rotation_angle, axis='x', anchor=0)
        # coil.move((i*0.1, 0, 0))
        sensor = magpy.Sensor(position=(1,0,5))
        sensor.rotate_from_angax(angle=rotation_angle, axis='x', anchor=0)
        print(coil.getB(sensor))
     
        x_data, y_data, z_data = np.mgrid[-6:6:30j, -6:6:30j, -6:6:30j]
        xyz_coordinates = np.c_[x_data.ravel(), y_data.ravel(), z_data.ravel()]

        B = magpy.getB(coil, xyz_coordinates)

        Bx = B[:, 0]
        By = B[:, 1]
        Bz = B[:, 2]
        Bx.shape = x_data.shape
        By.shape = y_data.shape
        Bz.shape = z_data.shape

        B_norm = np.sqrt(Bx ** 2 + By ** 2 + Bz ** 2)

        B_max_max = np.max(B_norm)
        index = np.argmax(B_norm)
        B_max_xyz_coordinates = xyz_coordinates[index]

        sensor_max = magpy.Sensor(position=B_max_xyz_coordinates)
        sensor_max.rotate_from_angax(angle=rotation_angle, axis='x', anchor=0)
        print(coil.getB(sensor_max))

**Comment by OrtnerMichael** [comment] 2021-07-24 20:51
hi @caimingxue 

Thanks for pointing this out. This is, however, not a Bug but expected from your code. When you rotate the Circular about 'x' and compute the field on a discrete static grid, then the distances between the Circular and your grid points will always be different - hence the change in max(amp(B)).



sincerely, michael

**Comment by caimingxue** [comment] 2021-07-25 03:36
Hi, @OrtnerMichael, thanks for your reply and answer. I still have some confusions. For a specific circular with constant parameters, if the discrete static grid is large enough and density enough, we suppose that the Max Value is always in the discrete static grid, the MAX magnitude of the field will keep similar or not dramatic change. That is, when the rotation angel (axis = x) is 0, we can get the MAX magnetic field in a 3D point (a, b, c) or some 3D point. When we rotate the circular (its center is in (0, 0, 0)) with 10 deg or some constant value, I find the MAX value will have dramatic change. Meanwhile,  if the (a, b, c) point rotate with same angle, we find that the magnetic value in this rotated point is different from Max value(dramatic change). I can understand the Max Value change small. If we set a sensor (u, v, w) and get the magnetic value in this point. When the sensor rotate a same angle with the filed, the magnetic value in the rotated sensor will keep same with before rotation. How to Explain this. I understand the magnetic field value change in the discrete grid point after rotation, but the magnetic field distribution should keep same.

**Comment by OrtnerMichael** [comment] 2021-07-25 09:16
Hi @caimingxue,

I understand your point, and it makes physically a lot of sense. However, the solutions implemented in Magpylib make some unphysical assumptions. In the case of Line and Circular currents there is an infinite line current density (infinitely small conductor cross section). This solution gives the same result as a homogeneous finite-sized current with circular cross-section would give - but only outside of the cross-section. On the inside it is not correct and would ofc depend on the cross-section diameter.

The Line and Circular solutions actually show a singularity (as can be expected when there is an infinite current density) when approaching the current-lines. This results in strongly changing fields whenever one of your observer points accidently lies close to the current-line. You will notice, that your max(amp(B)) will infinitely change just by adjusting your grid finesse - without rotation.

**Comment by OrtnerMichael** [comment] 2021-08-03 06:09
closing this now

**Closed by OrtnerMichael** 2021-08-03 06:09 UTC
