### ISSUE TITLE
[BUG] - Box DocString is wrong

### ISSUE THREAD

**Issue by JohnnyGG273** [magpylib/magpylib#352] opened 2021-07-06 12:30 UTC
**DocString Issue with Class Box**
In Visual Studio Code the wrong DocString for the class Box is shown, when hovering over it.
It seems like it is from an previous version but the one in the code seems to be the right one

**To Reproduce**
Steps to reproduce the behavior (in VSC!!):

 - Open the DocString of the magpylib.magnet.Box class
 - Hover over an Box Object with your mouse

**Expected behavior**
The DocString which is written in the class should be shown, but instead an old version is displayed.

**Screenshots**
![Screenshot (122)](https://user-images.githubusercontent.com/87006469/124599311-d31eb400-de65-11eb-830a-aeebb6a193a7.png)

**Desktop:**
 - OS: Windows 10 (64-Bit)
 - IDE: Visual Studio Code (1.57.1)

**Comment by lucasgcb** [comment] 2021-07-06 19:09
Hi, Johnny, thanks for contacting us. 

I've checked this on a fresh python environment, and it seems to be working as intended. 

Please answer the following so we can narrow the problem:

- Were you using magpylib v2 before? 
- What Python Extension are you using? 
- Are you using conda and pip at the same time?
- Do you have the correct python environment (the one with magpylib v3) enabled in your Editor? 
- What's the output for the `pip freeze` command in your terminal?

Thank you. Reminder that [we also have the docs for browsing online](https://magpylib.readthedocs.io/en/latest/_autogen/magpylib.magnet/), as well.

**Comment by JohnnyGG273** [comment] 2021-07-07 14:36
1. yes i used magpylib2, but in a differend environment
2.  ms-toolsai.jupyter & ms-python/python
3. yes i do, because numpy doesn't work as conda in my environment
4. yes, i've checked this very often
5. 
![image](https://user-images.githubusercontent.com/87006469/124778360-392c3980-df41-11eb-94eb-9740cf7e9486.png)

Thank you for your help, i already work with your online docs because of this error.

**Comment by Alexboiboi** [comment] 2021-11-05 11:17
This issue does no seem to be directly related to the `magpylib` library.

Keep in mind, that the representation of objects in v4 is going to be simplified.

Closing this issue, feel free to reopen it, if it becomes relevant again

**Closed by Alexboiboi** 2021-11-05 11:17 UTC
