### ISSUE TITLE
[REQUEST] When I use animation.FuncAnimation to make animation of source, including move and rotation in real time, the history info of source will keep all time by using display

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#382] opened 2021-08-31 09:34 UTC
**Is your feature request related to some problem? If yes, please describe.**

**Describe the feature you'd like**

**Describe alternatives or solutions you've considered**

**Additional context**

**Comment by OrtnerMichael** [comment] 2021-08-31 12:57
sorry thats too vague. Please describe the problem in more detail.

**Comment by caimingxue** [comment] 2021-08-31 13:27
> sorry thats too vague. Please describe the problem in more detail.
this is a part of the code to show an animation of coil rotation. The problem is the display function, which can not eliminate the trajectory of the coil
def animate(simData):
    # ax.collections = []  # clear lines streamplot
    # ax.patches = []  # clear arrowheads streamplot
    coil_c.rotate_from_angax(np.rad2deg(simData[3]), 'x', anchor=COIL_C.GetCoilOrigin(coil_c))
    print('=========================================', np.rad2deg(simData[1]),
          np.rad2deg(simData[2]), np.rad2deg(simData[3]))

    coil_c.display(axis=ax, markers=[COIL_A.GetCoilOrigin(coil_a)])
anim = animation.FuncAnimation(fig, animate, simData, interval=200, blit=False,
                               repeat=True)

plt.show()
this is the animation result when rotating a coil
<img width="825" alt="bug-1" src="https://user-images.githubusercontent.com/45029643/131510006-fd1b2b5e-b8d4-4573-8f2f-1762b0b15f36.png">
<img width="815" alt="bug-2" src="https://user-images.githubusercontent.com/45029643/131510025-8260d20e-bf40-432a-be99-c5b64d2ac784.png">

**Comment by lucasgcb** [comment] 2021-08-31 14:09
Hi caimingxue,

I'm not able to run the code you've provided. Please provide a code snippet anyone can run so more people can understand your situation.

**Comment by OrtnerMichael** [comment] 2021-08-31 20:46
The problem is that you create a Matplotlib plotting canvas ``ax``. Then you use the ``magpy.display(axis=ax)`` function to plot on that canvas repeated times. As a result you see multiple plots on top of each other. The same will happen when you use simple ``ax.plot(something)`` repeated times.

You have to create a new, empty figure every time before you add it to your animation - or you delete what you already put there in the step before.

**Comment by Alexboiboi** [comment] 2021-11-09 16:23
closing this, as it is not really a `magpylib` issue and more a `matplotlib` related one ;)

Feel free to reopen it if there is more to it

**Closed by Alexboiboi** 2021-11-09 16:23 UTC
Labels: no fix - not our problem
